export class ApparetmentInfo {
    MSSubClass: number;
    MSZoning: number;
    LotFrontage: number;
    LotArea: number;
    Street: number;
    Alley: number;
    LotShape: number;
    LandContour: number;
    Utilities: number;
    LandSlope: number;
    Neighborhood: number;
    Condition1: number;
    Condition2: number;
    BldgType: number;
    HouseStyle: number;
    OverallQual: number;
    OverallCond: number;
    YearBuilt: number;
    YearRemodAdd: number;
    RoofStyle: number;
    RoofMatl: number;
    Exterior1st: number;
    Exterior2nd: number;
    MasVnrType: number;
    MasVnrArea: number;
    ExterQual: number;
    ExterCond: number;
    Foundation: number;
    BsmtQual: number;
    BsmtCond: number;
    BsmtExposure: number;
    BsmtFinType1: number;
    BsmtFinSF1: number;
    BsmtFinType2: number;
    BsmtFinSF2: number;
    BsmtUnfSF: number;
    TotalBsmtSF: number;
    Heating: number;
    HeatingQC: number;
    CentralAir: number;
    Electrical: number;
    LowQualFinSF: number;
    GrLivArea: number;
    BsmtFullBath: number;
    BsmtHalfBath: number;
    FullBath: number;
    HalfBath: number;
    BedroomAbvGr: number;
    KitchenAbvGr: number;
    KitchenQual: number;
    TotRmsAbvGrd: number;
    Functional: number;
    Fireplaces: number;
    FireplaceQu: number;
    GarageType: number;
    GarageYrBlt: number | null; // Double en Java peut être null en TS
    GarageFinish: number;
    GarageCars: number;
    GarageArea: number;
    GarageQual: number;
    GarageCond: number;
    PavedDrive: number;
    WoodDeckSF: number;
    OpenPorchSF: number;
    EnclosedPorch: number;
    ScreenPorch: number;
    PoolArea: number;
    PoolQC: number;
    Fence: number;
    MiscFeature: number;
    MiscVal: number;
    MoSold: number;
    YrSold: number;
    SaleType: number;
    SaleCondition: number;

    constructor() {
        // Initialisation des valeurs par défaut si nécessaire
        this.MSSubClass = 0;
        this.MSZoning = 0;
        this.LotFrontage = 0;
        this.LotArea = 0;
        this.Street = 0;
        this.Alley = 0;
        this.LotShape = 0;
        this.LandContour = 0;
        this.Utilities = 0;
        this.LandSlope = 0;
        this.Neighborhood = 0;
        this.Condition1 = 0;
        this.Condition2 = 0;
        this.BldgType = 0;
        this.HouseStyle = 0;
        this.OverallQual = 0;
        this.OverallCond = 0;
        this.YearBuilt = 0;
        this.YearRemodAdd = 0;
        this.RoofStyle = 0;
        this.RoofMatl = 0;
        this.Exterior1st = 0;
        this.Exterior2nd = 0;
        this.MasVnrType = 0;
        this.MasVnrArea = 0;
        this.ExterQual = 0;
        this.ExterCond = 0;
        this.Foundation = 0;
        this.BsmtQual = 0;
        this.BsmtCond = 0;
        this.BsmtExposure = 0;
        this.BsmtFinType1 = 0;
        this.BsmtFinSF1 = 0;
        this.BsmtFinType2 = 0;
        this.BsmtFinSF2 = 0;
        this.BsmtUnfSF = 0;
        this.TotalBsmtSF = 0;
        this.Heating = 0;
        this.HeatingQC = 0;
        this.CentralAir = 0;
        this.Electrical = 0;
        this.LowQualFinSF = 0;
        this.GrLivArea = 0;
        this.BsmtFullBath = 0;
        this.BsmtHalfBath = 0;
        this.FullBath = 0;
        this.HalfBath = 0;
        this.BedroomAbvGr = 0;
        this.KitchenAbvGr = 0;
        this.KitchenQual = 0;
        this.TotRmsAbvGrd = 0;
        this.Functional = 0;
        this.Fireplaces = 0;
        this.FireplaceQu = 0;
        this.GarageType = 0;
        this.GarageYrBlt = null;
        this.GarageFinish = 0;
        this.GarageCars = 0;
        this.GarageArea = 0;
        this.GarageQual = 0;
        this.GarageCond = 0;
        this.PavedDrive = 0;
        this.WoodDeckSF = 0;
        this.OpenPorchSF = 0;
        this.EnclosedPorch = 0;
        this.ScreenPorch = 0;
        this.PoolArea = 0;
        this.PoolQC = 0;
        this.Fence = 0;
        this.MiscFeature = 0;
        this.MiscVal = 0;
        this.MoSold = 0;
        this.YrSold = 0;
        this.SaleType = 0;
        this.SaleCondition = 0;
    }
}